### ISSUE TITLE
Not working with Ogame 7.0

### ISSUE THREAD

**Issue by SiR-DanieL** [Chewbaka69/ogame-ui-firefox#2]
After the update of Ogame 7.0 this extension does not work. It shows the buttons in the menu, but clicking them does nothing.

**Comment by Chewbaka69** [comment]
I will work on it to fix this.

**Comment by Chewbaka69** [comment]
I have somme bug, but it takes many times to fix all

**Comment by Chewbaka69** [comment]
I have fixed some bugs and i publish a new version today.

**Comment by SiR-DanieL** [comment]
Thank you!

**Comment by Chewbaka69** [comment]
Waiting mozilla validation.
