### ISSUE TITLE
How do i install it?

### ISSUE THREAD

**Issue by Brasgaard** [Chewbaka69/ogame-ui-firefox#3]
Hi,

I would like to install this extension, but how do i do it? Thanks!

**Comment by Chewbaka69** [comment]
Next time reade the README.MD:
=> https://addons.mozilla.org/en-US/firefox/addon/ogame-ui-extension/

**Comment by Brasgaard** [comment]
Sorry about that! :)
I have the same issue as the other guy if then clicking the button in game it doesnt do anything. Is their any news on the process there?

**Comment by Chewbaka69** [comment]
I have fix the plug-in to work on Ogame 6.x and 7.x.
In what version do you play?
