### ISSUE TITLE
Addon stopped working properly (FireFox & Chrome version) (On 2 different PC)

### ISSUE THREAD

**Issue by joeldubreuil** [Chewbaka69/ogame-ui-firefox#4]
For some reason, Addon is loaded but doesn't work as it was earlier this week.

- Ressources Time CountDown aren't working
- Ogame UI++ button is there but not working
- Links to TrashSim are now missing  

Maybe a patch/change on ogame website creates an issue ?

**Comment by Chewbaka69** [comment]
Hummm, maybe ogame has update the website, yes.
So I will check it today.

**Comment by dauge** [comment]
Did you find something ?

**Comment by Chewbaka69** [comment]
Yes I have found some content that change on Ogame.
I will fix it in few days.

**Comment by Chewbaka69** [comment]
I have fix it. I will publish soon

**Comment by Chewbaka69** [comment]
Published!
