### ISSUE TITLE
Extension stopped working on Firefox

### ISSUE THREAD

**Issue by ferograd** [Chewbaka69/ogame-ui-firefox#8]
So I have been in V-Mode for over a month and over the course of this time the Uni I play in have been upgraded to the new version.

For some reason on Firefox this extension have stopped working completely. All I have is the "Statistic" and "OgameUI++" buttons on the sidebar but clicking on them only highlights them and nothing else....

No other functionality of the extension works either

I am new to reporting any of these so let me know what info you need...

I am running Firefox 71.0 (32-bit)

Cheers

**Comment by Chewbaka69** [comment]
What is the version of your universe?

**Comment by ferograd** [comment]
It's 7.1.0-rc15 (If I am reading it at the right place)

**Comment by Chewbaka69** [comment]
Did you use other script ?

**Comment by ferograd** [comment]
The usual:

Antigame Origin
Universe View

It works at home on Chrome...

**Comment by ferograd** [comment]
Scrap that.... It does not work anymore on chrome either (Just checked now)

**Comment by Chewbaka69** [comment]
Ok there is a incompatibility with antigame. I will check it why.

**Comment by Chewbaka69** [comment]
I have publish now the new version say me if the bug is fix

**Comment by ferograd** [comment]
Still the same I'm afraid =(

Even when I disable Antigame extension

**Comment by Chewbaka69** [comment]
The version is on even publish on firefox we need to wait firefox validated it

**Comment by Chewbaka69** [comment]
Check if you have the version 3.19.2 on firefox

**Comment by ferograd** [comment]
Sorry... Version of what? The extension?

I am not at work at present and use chrome instead which exhibits the same
issue

**Comment by Chewbaka69** [comment]
I am not the dev of the chrome extension so i can't update it. I only update the firefox version.

**Comment by ferograd** [comment]
Do you know who I can contact regarding the chrome extension?

It looks after Kalyke upgraded to the new universe version pretty much all
the freaking extensions got bugged =/

**Comment by Chewbaka69** [comment]
You can go there:
https://github.com/eswak/chrome-ogame-ui-extension

But there are a lot of issue to update it.

**Comment by ferograd** [comment]
Still the same mate

Disabling antigame on Chrome didn't change anything

Do you need any info?

**Comment by ferograd** [comment]
Trying to update extension from within Firefox didn't work

Removed and re-added it from the add-on store seems to get it working again

Thanks
